# Generated by Django 5.0.4 on 2024-04-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
