# Generated by Django 5.0.4 on 2024-04-30 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_nacionalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nacionalidad',
        ),
        migrations.AddField(
            model_name='cliente',
            name='nacionalidad_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.nacionalidad'),
        ),
    ]
